name: cellsim
channels:
  - defaults
  - torch
  - xformers
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - xformers::xformers>=0.0.18
  - torchmetrics
  - torchdata
  - omegaconf
  - fvcore
  - iopath
  - pip
  - pip:
      - --index-url https://download.pytorch.org/whl/cu118
      - pytorch::torch==2.3.0+cu118
      - pytorch::torchvision
      - pytorch::pytorch-cuda
      - git+https://github.com/facebookincubator/submitit
      - --extra-index-url https://pypi.nvidia.com
      - cuml-cu11

