train:
  dataset_path: /home/manon/classification/data/Single_cells/medhi
  output_dir: /home/guevel/OT4D/cell_similarity/src/cell_similarity/scripts/memory_test2_out
  batch_size_per_gpu: 32
  OFFICIAL_EPOCH_LENGTH: 20
student:
  arch: vit_large
  block_chunks: 4
