train:
  batch_size: 64
  dataset_path: /home/etienneguevel/Documents/SCAI/OT4D/cell_similarity/datasets/PBC_dataset_normal_DIB
  num_epochs: 10
  output_dir: /home/etienneguevel/Documents/SCAI/OT4D/cell_similarity/outputs
model:
  lr: 0.0001
  momemtum: 0.9
encoder:
  type: dinov2
  arch: vit_large
  num_register_tokens: 0
  pretrained_weights: ''
  rch: vit_large
  patch_size: 16
  drop_path_rate: 0.3
  layerscale: 1.0e-05
  drop_path_uniform: true
  ffn_layer: mlp
  block_chunks: 0
  qkv_bias: true
  proj_bias: true
  ffn_bias: true
  interpolate_antialias: false
  interpolate_offset: 0.1
