preprocess:
  dataset_path: /home/manon/classification/data/Single_cells/barcelona
  cache_path: /home/guevel/OT4D/cell_similarity/projection/cache
  batch_size: 128

train:
  batch_size: 64
  output_dir: /home/guevel/OT4D/cell_similarity/projection/model
  max_epochs: 2000000
  
student:
  arch: vit_large
  block_chunks: 4
