preprocess:
  dataset_path: /home/manon/classification/data/Single_cells/barcelona
  cache_path: /home/guevel/OT4D/cell_similarity/projection/cache
  batch_size: 128

train:
  batch_size: 64
  output_dir: /home/guevel/OT4D/cell_similarity/projection/model
  max_epochs: 20000
  num_workers: 10

model:
  lr: 1e-3
  momentum: 0.9

encoder:
  type: dinov2
  arch: vit_large
  patch_size: 16
  drop_path_rate: 0.3
  layerscale: 1.0e-05
  drop_path_uniform: true
  pretrained_weights: ''
  ffn_layer: "mlp"
  block_chunks: 0
  qkv_bias: true
  proj_bias: true
  ffn_bias: true
  num_register_tokens: 0
  interpolate_antialias: false
  interpolate_offset: 0.1
